compressionLevel: 0

enableGlobalCache: false

enableScripts: true

nodeLinker: pnp

packageExtensions:
  recma-jsx@*:
    dependencies:
      acorn: '*'

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.10.3.cjs
