enableGlobalCache: false

enableScripts: true

nodeLinker: pnp
compressionLevel: 0

packageExtensions:
  recma-jsx@*:
    dependencies:
      acorn: '*'

pnpMode: strict
pnpPath: ./.pnp.cjs

yarnPath: .yarn/releases/yarn-4.9.3.cjs
