enableGlobalCache: false

enableScripts: true

nodeLinker: pnp
compressionLevel: 0

packageExtensions:
  '@serwist/next@*':
    dependencies:
      '@serwist/webpack-plugin': '*'
  '@serwist/webpack-plugin@*':
    dependencies:
      '@serwist/build': '*'

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.9.3.cjs
